"""Generate firmware/stm32/protocol/tests/golden_vectors.h from docs/PROTOCOL.md.

The C protocol library and the Python one (storemind/storemind/sensors/protocol.py)
must agree byte for byte.  This script takes every example line from PROTOCOL.md
(```text = must decode, ```invalid = must be rejected for the reason after '#')
plus CRC-16 and COBS vectors computed by the Python implementation, and writes
them as a C header the host tests run against.

    python firmware/stm32/tools/gen_golden.py            # rewrite the header
    python firmware/stm32/tools/gen_golden.py --check    # exit 1 if it is stale

`storemind/tests/test_firmware_golden.py` runs the --check logic in pytest, so a
change to PROTOCOL.md that is not regenerated fails CI.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DOC = ROOT / "docs" / "PROTOCOL.md"
OUT = ROOT / "firmware" / "stm32" / "protocol" / "tests" / "golden_vectors.h"
sys.path.insert(0, str(ROOT / "storemind"))

from storemind.sensors.protocol import cobs_encode, crc16_ccitt  # noqa: E402

# Binary vectors: short, zero-heavy, and the 254-byte block boundary.
BINARY_VECTORS: list[bytes] = [
    b"",
    b"\x00",
    b"123456789",                       # CRC-16/CCITT-FALSE check value 0x29B1
    b"\x11\x22\x00\x33",
    b"\x00\x00",
    bytes(range(1, 255)),               # exactly one full COBS block
    bytes(range(1, 256)),               # one byte past it
    bytes([0x57, 17]) + (523040).to_bytes(4, "little") + b"\x00\x00\x30\x07\x01",
]


def blocks(text: str, lang: str) -> list[str]:
    lines: list[str] = []
    for block in re.findall(rf"```{lang}\n(.*?)```", text, flags=re.DOTALL):
        lines += [line.strip() for line in block.splitlines() if line.strip()]
    return lines


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_bytes(data: bytes) -> str:
    if not data:
        return "{0}"
    return "{" + ", ".join(f"0x{b:02X}" for b in data) + "}"


def render() -> str:
    text = DOC.read_text(encoding="utf-8")
    valid = blocks(text, "text")
    invalid = []
    for entry in blocks(text, "invalid"):
        line, _, reason = entry.partition("#")
        invalid.append((line.strip(), reason.strip()))

    out = [
        "/* GENERATED by firmware/stm32/tools/gen_golden.py from docs/PROTOCOL.md.",
        " * Do not edit: change PROTOCOL.md and re-run the script. */",
        "#ifndef GOLDEN_VECTORS_H",
        "#define GOLDEN_VECTORS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "/* Every ```text example: must decode, and re-encode to the same bytes. */",
        "static const char *const GOLDEN_VALID[] = {",
    ]
    out += [f"    {c_string(line)}," for line in valid]
    out += ["};", "",
            "/* Every ```invalid example and the reason it must be rejected for. */",
            "typedef struct { const char *line; const char *reason; } golden_invalid_t;",
            "static const golden_invalid_t GOLDEN_INVALID[] = {"]
    out += [f"    {{{c_string(line)}, {c_string(reason)}}}," for line, reason in invalid]
    out += ["};", "",
            "/* CRC-16/CCITT-FALSE and COBS, computed by sensors/protocol.py. */",
            "typedef struct { size_t len; uint8_t data[256]; uint16_t crc;",
            "                 size_t cobs_len; uint8_t cobs[260]; } golden_binary_t;",
            "static const golden_binary_t GOLDEN_BINARY[] = {"]
    for data in BINARY_VECTORS:
        encoded = cobs_encode(data)
        out.append(f"    {{{len(data)}, {c_bytes(data)}, 0x{crc16_ccitt(data):04X}, "
                   f"{len(encoded)}, {c_bytes(encoded)}}},")
    out += ["};", "", "#endif /* GOLDEN_VECTORS_H */", ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the header is out of date")
    args = parser.parse_args()
    fresh = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != fresh:
            print(f"{OUT} is stale: run python firmware/stm32/tools/gen_golden.py", file=sys.stderr)
            return 1
        print("golden vectors up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(fresh, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
